title: HCNI@CHIPLAY 2025
description: Welcome to the First Interdisciplinary Workshop on Human-Computer Narrative Interactions (HCNI) at CHI PLAY 2025! We'll engage in hands-on exploration of player-game interactivity for impactful digital storytelling. All disciplines and experience levels welcome!
github:
  is_project_page: false

# theme: jekyll-theme-minimal
# theme: jekyll-theme-architect
# theme: jekyll-theme-slate
# theme: jekyll-theme-cayman

remote_theme: jekyll/minima
author:
    email: g38smith@uwaterloo.ca

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - objectives.md
  - activities.md
  - call-for-participation.md
  - organizers.md

minima:
  skin: classic
  hide_site_feed_link: true
  nav_pages:
    - objectives.md
    - activities.md
    - call-for-participation.md
    - organizers.md